---
- name: Install php5
  sudo: yes
  apt: pkg=php5 state=latest

- name: Add php.ini template to mod_php
  template: src="php.ini.j2"
            dest="/etc/php5/apache2/php.ini"
  notify: restart apache

- name: Add php.ini template to cli
  template: src="php.ini.j2"
            dest="/etc/php5/cli/php.ini"
  notify: restart apache

- name: PHP | Removed cli php.ini disabled_functions
  sudo: yes
  lineinfile: dest=/etc/php5/cli/php.ini regexp="^disable_functions" state=absent
  notify: restart apache
